### ISSUE TITLE
Feature: Convert UndiciRequest to support html content type

### ISSUE THREAD

**Issue by brainrepo** [GitbarPodcast/Botletter#35]
# Story
To support the work of the Enricher #28, we need that UndiciRequest supports to the HTML content-type requests.

# Blockers
#10 Airtable persisted adapter that introduces the undiciRequest and the networking functions

# QA
I can use undiciRequest to make calls to an endpoint returns HTML content

**Comment by sf3ris** [comment]
Hey, I would like to start my contribution with this issue. Can i try to give it a shot? :smile:

**Comment by brainrepo** [comment]
Sure! 

> Hey, I would like to start my contribution with this issue. Can i try to give it a shot? 😄

Sure! Thx.

**Comment by sf3ris** [comment]
I linked the wrong issue on the PR. :facepalm:  I think this issue can be closed
