### ISSUE TITLE
UndiciRequest

### ISSUE THREAD

**Issue by brainrepo** [GitbarPodcast/Botletter#38]
In this issue, we will discuss the @LucaRainone proposal related to #10. 
He suggests renaming UndiciRequest.ts -> Request.ts.

_I think we shouldn't call this file "undiciRequest" because the scope is to make the rest of code "library-agnostic" (right?).
If we change undici with "got" we must rename all import statements everywhere.
Maybe we can simply call it "request.ts"._

Luca's proposal makes sense, but I called **UndiciRequest**  because it is an adapter of Undici for our systems, If we want to use got we will create another file called **GotRequest**.

@LucaRainone , did I understood good? 
Guys, what do you think about it?

**Comment by LucaRainone** [comment]
Yes. The main reason for my change request is that probably we'll never get two or more libraries for http requests at the same time. A most probable scenario is to change the base library, without changing its behaviour, input and output. The application level should work with a simple generic wrapper

**Comment by Raibaz** [comment]
I tend to agree with @LucaRainone's point: I like the idea of wrapping requests in a level of abstraction so that changing the request library can be done transparently.

**Comment by CDimonaco** [comment]
I agree with the idea of request wrapper, the domain, and usecase part of
the application, should not be aware of any library request.

Furthermore it's simpler to test the business logic part with an
abstraction, rather than mock all the infrastructure things

**Comment by CDimonaco** [comment]
If we don't have yet the domain part, we will create later an interface for
this dependency, and we will adapt if needed the wrapper to the interface.

**Comment by brainrepo** [comment]
MY 2.5 cents 🪙  I think the concept of request is related to the infrastructure layer, then I don't think is a good idea to put it inside the domain. 
In my opinion, the domain should interact with more generic concepts like message sender (its interface with the Mailchimp implementation) and state. The logic that uses the **request implementation/interface** to call Mailchimp API and airtable API should stay inside the infrastructure API. Then I suggest that: the request interface can be useful to allow us to implement other HTTP request adapters and to allow us to do easier testing.
